repos:
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    # Run Black - the uncompromising Python code formatter
    - id: black
    # Run Black - the uncompromising Python code formatter (Jupyter version)
    - id: black-jupyter

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # Ensure existence of newline characters at file ends
    - id: end-of-file-fixer
    # Make sure that contained YAML files are well-formed
    - id: check-yaml
    # Trim trailing whitespace of all sorts
    - id: trailing-whitespace
    # Apply a file size limit of 500kB
    - id: check-added-large-files
    # Simple parser validation of e.g. pyproject.toml
    - id: end-of-file-fixer
    # Sort lines in requirements files
    - id: mixed-line-ending

- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
    # GitHub Actions Workflow linter
    - id: actionlint
